jobs:
  build-native-images:
    environment: Build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Code
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Build Java components
      run: mvn -B -DskipTests -Pprod install
    - continue-on-error: true
      name: Set IMAGE_TAG environment from input
      run: 'set -x

        echo "IMAGE_TAG=${{ inputs.image-tag }}-native" >> "$GITHUB_ENV"

        '
    - continue-on-error: true
      if: matrix.arch == 'arm64'
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: ${{ matrix.arch }}
    - continue-on-error: true
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        install: true
    - continue-on-error: true
      if: matrix.arch == 'amd64'
      name: Set builder image for amd64
      run: 'echo "BUILDER_IMAGE=paketobuildpacks/builder-jammy-base:latest" >> "$GITHUB_ENV"

        echo "RUNNER_IMAGE=paketobuildpacks/run-jammy-base:latest" >> "$GITHUB_ENV"

        '
    - continue-on-error: true
      if: matrix.arch == 'arm64'
      name: Set builder image for arm64
      run: 'echo "BUILDER_IMAGE=dashaun/builder@sha256:378bdc9fd7bdba105d64f294a8a7ca168dce5e496cad22307ccabb66fb571f9a"
        >> "$GITHUB_ENV"

        echo "RUNNER_IMAGE=dmikusa/run-jammy-base@sha256:01d2f750569d14b0374dfa3f9f106ada23ff3dfa68f2ac33fb95d3d8e058b5e9"
        >> "$GITHUB_ENV"

        '
    - continue-on-error: true
      name: Build native image for ${{ matrix.arch }}
      run: "cd ${{github.workspace}}/distro/uber\nmvn -Pnative spring-boot:build-image\
        \ -Dspring-boot.build-image.imageName=microcks/microcks-uber:$IMAGE_TAG-${{\
        \ matrix.arch }} \\\n    -Dspring-boot.build-image.builder=$BUILDER_IMAGE\
        \ \\\n    -Dspring-boot.build-image.runImage=$RUNNER_IMAGE\n"
    - continue-on-error: true
      name: Save native image for ${{ matrix.arch }}
      uses: ishworkh/docker-image-artifact-upload@v1
      with:
        image: microcks/microcks-uber:${{ env.IMAGE_TAG }}-${{ matrix.arch }}
    strategy:
      matrix:
        arch:
        - amd64
        - arm64
  create-app-multiarch-manifests:
    environment: Build
    needs: push-app-images
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Set IMAGE_TAG environment from input
      run: 'echo "IMAGE_TAG=${{inputs.image-tag}}-native" >> "$GITHUB_ENV"

        '
    - continue-on-error: true
      name: Login to Quay.io and Docker Hub registries
      run: 'echo ${{ secrets.QUAY_PASSWORD }} | docker login -u ${{ secrets.QUAY_USERNAME
        }} --password-stdin quay.io

        echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME
        }} --password-stdin docker.io

        '
    - continue-on-error: true
      name: Create and push multi-arch manifests
      run: "docker manifest create quay.io/microcks/microcks-uber:${{ env.IMAGE_TAG\
        \ }} \\\n  -a quay.io/microcks/microcks-uber:${{ env.IMAGE_TAG }}-amd64 \\\
        \n  -a quay.io/microcks/microcks-uber:${{ env.IMAGE_TAG }}-arm64\ndocker manifest\
        \ push quay.io/microcks/microcks-uber:${{ env.IMAGE_TAG }}\ndocker manifest\
        \ create docker.io/microcks/microcks-uber:${{ env.IMAGE_TAG }} \\\n  -a docker.io/microcks/microcks-uber:${{\
        \ env.IMAGE_TAG }}-amd64 \\\n  -a docker.io/microcks/microcks-uber:${{ env.IMAGE_TAG\
        \ }}-arm64\ndocker manifest push docker.io/microcks/microcks-uber:${{ env.IMAGE_TAG\
        \ }}\n"
      shell: bash
  push-app-images:
    environment: Build
    needs: build-native-images
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Set IMAGE_TAG environment from input
      run: 'echo "IMAGE_TAG=${{inputs.image-tag}}-native" >> "$GITHUB_ENV"

        '
    - continue-on-error: true
      name: Get saved images for ${{ matrix.arch }}
      uses: ishworkh/docker-image-artifact-download@v1
      with:
        image: microcks/microcks-uber:${{ env.IMAGE_TAG }}-${{ matrix.arch }}
    - continue-on-error: true
      name: Login to Quay.io and Docker Hub registries
      run: 'echo ${{ secrets.QUAY_PASSWORD }} | docker login -u ${{ secrets.QUAY_USERNAME
        }} --password-stdin quay.io

        echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME
        }} --password-stdin docker.io

        '
    - continue-on-error: true
      name: Tag image
      run: 'docker tag microcks/microcks-uber:${{ env.IMAGE_TAG }}-${{ matrix.arch
        }} quay.io/microcks/microcks-uber:${{ env.IMAGE_TAG }}-${{ matrix.arch }}

        docker tag microcks/microcks-uber:${{ env.IMAGE_TAG }}-${{ matrix.arch }}
        docker.io/microcks/microcks-uber:${{ env.IMAGE_TAG }}-${{ matrix.arch }}

        '
    - continue-on-error: true
      name: Push image
      run: 'docker push quay.io/microcks/microcks-uber:${{ env.IMAGE_TAG }}-${{ matrix.arch
        }}

        docker push docker.io/microcks/microcks-uber:${{ env.IMAGE_TAG }}-${{ matrix.arch
        }}

        '
    strategy:
      matrix:
        arch:
        - amd64
        - arm64
name: package-native
on:
  repository_dispatch:
    types: trigger-ga___package-native.yml
